spring:
  application:
    name: only-danmuku
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  mvc:
    log-request-details: true

  datasource:
    url: jdbc:mysql://localhost:3306/only_danmuku?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 30
      max-active: 100
      min-idle: 30
      max-wait: 1000
      use-unfair-lock: true
      pool-prepared-statements: false
      validation-query: select 1
      validation-query-timeout: 2
      keep-alive: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      min-evictable-idle-time-millis: 43200000
      max-evictable-idle-time-millis: 86400000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      # 地址
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # redis 密码必须配置
      password: 123456
      # 连接超时时间
      timeout: 10s
      # 是否开启ssl
      ssl.enabled: false

logging:
  level:
    sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.boot.autoconfigure.condition: DEBUG

only:
  engine:
    json:
      enable: true
    captcha:
      enable: true
      provider:
        store: redis
    redis:
      enable: true
    # redisson 配置
    redisson:
      # redis key前缀
      keyPrefix:
      # 线程池数量
      threads: 4
      # Netty线程池数量
      nettyThreads: 8
      # 单节点配置
      singleServerConfig:
        # 客户端名称 不能用中文
        clientName: ONLY-DANMUKU
        # 最小空闲连接数
        connectionMinimumIdleSize: 8
        # 连接池大小
        connectionPoolSize: 32
        # 连接空闲超时，单位：毫秒
        idleConnectionTimeout: 10000
        # 命令等待超时，单位：毫秒
        timeout: 3000
        # 发布和订阅连接池大小
        subscriptionConnectionPoolSize: 50
    sa-token:
      enable: true
    security:
      enable: true
      provider:
        security-interceptor: "sa-token"
    web:
      filter:
        health-check:
          enable: true
        request-body:
          enable: true
      advice:
        base-packages: [ "edu.only4.danmuku" ]
        response-wrapper:
          enable: true
        global-exception-handler:
          enable: true
      performance-interceptor:
        enable: true

cap4k:
  ddd:
    arch-info:
      enabled: true
      base-package: edu.only4.danmuku
    distributed:
      id-generator:
        snowflake:
          enable: true
    domain:
      event:
        event-scan-package: ${cap4k.ddd.archinfo.base-package}
        schedule:
          add-partition-enable: false
    application:
      saga:
        schedule:
          add-partition-enable: false
      request:
        schedule:
          add-partition-enable: false

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 400

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # jwt秘钥
  jwt-secret-key: abcdefghijklmnopqrstuvwxyz

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,shutdown
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    redis:
      enabled: false

jimmer:

  # This is very important,
  # With this configuration,
  # `jimmer-spring-starter` will create `KSqlClient` for kotlin;
  # otherwise, it will create `JSqlClient` for java.
  language: kotlin

  database-validation-mode: ERROR
  show-sql: true
  pretty-sql: true

app:
  file:
    project-folder: C:/Users/LD_moxeii/Documents/only-danmuku-file/
    show-f-fmpeg-log: true
